name: API Test Workflow

on:
  workflow_dispatch:  # 수동 실행 허용
  push:
    branches:
      - main
  schedule:  # 스케줄 기반 실행 (크론 표현식 사용)
    - cron: "0 2 * * 1-5" # UTC 기준 2시 (KST 11:00)
    
jobs:
  api-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Run Postman tests with Newman
        env:
          KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}  # GitHub Secrets에서 API Key 불러오기
        run: |
          newman run your_postman_collection.json --env-var KAKAO_API_KEY=$KAKAO_API_KEY
